// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eifhxvmdfpwtmmlzegpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZmh4dm1kZnB3dG1tbHplZ3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODkxMzQsImV4cCI6MjA3Mzg2NTEzNH0.f8-H8dIpKTEWEYxxq4jmUm0PzD2-JM4lD5fyh5AEYt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});